version: "3.9"

services:
  mysql:
    image: mysql:8.3.0
    container_name: veltrionix-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE : home_energy_tracker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
#      - ./init/mysql_init.sql:/docker-entrypoint-initdb.d/mysql_init.sql
      - ./init:/docker-entrypoint-initdb.d
volumes:
  mysql_data:
